language: node_js
node_js:
- "7"

script: npm run build

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ];then exit 0; fi'
  - surge --project dist --domain hyperapp-website-pr-$TRAVIS_PULL_REQUEST.surge.sh

deploy:
  fqdn: hyperapp.js.org
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  email: false
